name: BeautyQuests
author: SkytAsul
version: "${human.version}_BUILD${build.number}"
#version: ${human.version}
description: Quests system with a simple graphical interface.
website: https://www.spigotmc.org/resources/beautyquests.39255/
api-version: 1.13
main: fr.skytasul.quests.BeautyQuests

softdepend:
- WorldGuard
- MythicMobs
- Vault
- PlaceholderAPI
- SkillAPI
- HolographicDisplays
- Jobs
- Factions
- AccountsHook
- dynmap
- EpicBosses
- GPS
- mcMMO
- McCombatLevel
- CMI
- TokenEnchant
- Boss
- UltimateTimber
- ServersNPC
- Citizens
- ProSkillAPI
- BlueMap
- Sentinel
- AdvancedSpawners
- DecentHolograms

#commands:
#  beautyquests:
#    description: Main command for quests
#    permission: beautyquests.command
#    aliases: [bquests, quests, beautyquests, bq, quest]
    
permissions:
  beautyquests.*:
    description: Gives access to BeautyQuests whole
    children:
      beautyquests.command: true
      beautyquests.command.*: true
      beautyquests.seeId: true
      beautyquests.start: true
  beautyquests.command:
    description: Gives access to "/quests"
    default: true
  beautyquests.command.*:
    description: Gives access to all subcommands of "/quests"
    children:
      beautyquests.command.listPlayer: true
      beautyquests.command.version: true
      beautyquests.command.create: true
      beautyquests.command.edit: true
      beautyquests.command.list: true
      beautyquests.command.help: true
      beautyquests.command.remove: true
      beautyquests.command.manage: true
      beautyquests.command.finish: true
      beautyquests.command.finishAll: true
      beautyquests.command.setStage: true
      beautyquests.command.setName: true
      beautyquests.command.resetPlayer: true
      beautyquests.command.seePlayer: true
      beautyquests.command.adminMode: true
      beautyquests.command.start: true
      beautyquests.command.start.other: true
      beautyquests.command.cancel: true
      beautyquests.command.cancel.other: true
      beautyquests.command.scoreboard: true
      beautyquests.command.scoreboard.toggle: true
      beautyquests.command.checkpoint: true
  beautyquests.command.listPlayer:
    decription: 'Gives access to the menu GUI'
    default: true
  beautyquests.command.version:
    decription: 'Gives access to the "/quests version"'
    default: true
  beautyquests.command.create:
    decription: 'Gives access to "/quests create"'
    default: op
  beautyquests.command.edit:
    decription: 'Gives access to "/quests edit"'
    default: op
  beautyquests.command.list:
    decription: 'Gives access to "/quests list"'
    default: op
  beautyquests.command.help:
    decription: 'Gives access to "/quests help"'
    default: true
  beautyquests.command.remove:
    decription: 'Gives access to "/quests remove"'
    default: op
  beautyquests.command.manage:
    decription: 'Gives access to "/quests reload" and some more management commands'
    default: op
  beautyquests.command.finish:
    decription: 'Gives access to "/quests finish" and "finishAll"'
    default: op
  beautyquests.command.setStage:
    decription: 'Gives access to "/quests setStage"'
    default: op
  beautyquests.command.setName:
    decription: 'Gives access to "/quests setName"'
    default: op
  beautyquests.command.resetPlayer:
    decription: 'Gives access to "/quests resetPlayer" and "resetPlayerQuest"'
    default: op
  beautyquests.command.seePlayer:
    decription: 'Gives access to "/quests seePlayer"'
    default: op
  beautyquests.command.setItem:
    decription: 'Gives access to "/quests setItem"'
    default: op
  beautyquests.command.adminMode:
    description: 'Gives access to "/quests adminMode"'
    default: op
  beautyquests.command.start:
    description: 'Gives access to "/quests start" only for executing player'
    default: op
  beautyquests.command.start.other:
    description: 'Gives access to "/quests start" for all players'
    default: op
  beautyquests.command.cancel:
    description: 'Gives access to "/quests cancel" only for my own started quests'
    default: op
  beautyquests.command.cancel.other:
    description: 'Gives access to "/quests cancel" for all players quests'
    default: op
  beautyquests.command.scoreboard:
    description: 'Gives access to "/quests scoreboard" to manage player scoreboards'
    default: op
  beautyquests.command.scoreboard.toggle:
    description: 'Gives access to "/quests scoreboard" to toggle player scoreboard'
    default: true
  beautyquests.command.pools:
    description: 'Gives access to "/quests pools"'
    default: op
  beautyquests.command.checkpoint:
    description: 'Allows player to use checkpoints'
    default: true
  beautyquests.seeId:
    description: 'Allows player to see the quest''s ID'
    default: op
  beautyquests.start:
    description: 'Allows player to start quests'
    default: true