name: Build

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDKs
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: |
            21
          # maybe necessary to add more since we want to compile for lower?
          cache: maven
      
      - name: Download private dependencies
        run: |
          mkdir jars
          curl -s https://skytasul.fr/protected/bq-jars.tar.gz --header 'Token: ${{ secrets.PrivateDownloadToken }}' --output - | tar xzfv - --directory ./jars

      - name: Install private dependencies
        run: "./integrations/libs.sh mvn ./jars"

      - name: Build and package with Maven
        run: |
          profile=$([ "${{ github.ref_name }}" == "${{ github.event.repository.default_branch }}" ] && echo "release" || echo "devbuild")
          echo "Building with profile $profile"
          mvn -B clean package --file pom.xml -Dbuild.number=${{ github.run_number }} -P $profile
    
      # We do not actually need the artifact since we create a release with it
      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     path: |
      #       target/*.jar

      - name: Prepare a release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'push'
        with:
          prerelease: ${{ github.ref_name != github.event.repository.default_branch }}
          draft: true
          name: "${{ github.ref_name }} - build ${{ github.run_number }}"
          tag_name: "build/${{ github.run_number }}"
          target_commitish: ${{ github.sha }}
          generate_release_notes: ${{ github.ref_name == github.event.repository.default_branch }}
          files: |
            target/*.jar
