name: Build

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request || github.event.pull_request.draft == false }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDKs
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: |
            21
          # maybe necessary to add more since we want to compile for lower?
          cache: maven
      
      - name: Download private dependencies
        run: |
          mkdir jars
          curl -s https://skytasul.fr/protected/bq-jars.tar.gz --header 'Token: ${{ secrets.PrivateDownloadToken }}' --output - | tar xzfv - --directory ./jars

      - name: Install private dependencies
        run: "./integrations/libs.sh mvn ./jars"

      - name: Install missing dependencies
        run: |
          curl -s https://skytasul.fr/SpigotUpdateChecker-3.0.3-offline.jar -o ./jars/SpigotUpdateChecker-3.0.3-offline.jar
          mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=./jars/SpigotUpdateChecker-3.0.3-offline.jar
          curl -s https://skytasul.fr/ConfigUpdater-2.2-SNAPSHOT-offline.jar -o ./jars/ConfigUpdater-2.2-SNAPSHOT-offline.jar
          mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=./jars/ConfigUpdater-2.2-SNAPSHOT-offline.jar

      - name: Build and package with Maven
        run: |
          profile=$([ "${{ github.ref_name }}" == "${{ github.event.repository.default_branch }}" ] && echo "release" || echo "devbuild")
          echo "Building with profile $profile"
          mvn -B clean package --file pom.xml -Dbuild.number=${{ github.run_number }} -P $profile
    
      # We do not actually need the artifact since we create a release with it
      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     path: |
      #       target/*.jar

      - name: Prepare a pre-release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'push' && github.ref_name != github.event.repository.default_branch
        with:
          prerelease: true
          draft: true
          name: "${{ github.ref_name }} - build ${{ github.run_number }}"
          tag_name: "build/${{ github.run_number }}"
          target_commitish: ${{ github.sha }}
          body: |-
            ### Note
            This is a **dev build** and not a release. Please use with care!
            - Backup your prior data before installing: both the `/plugins/BeautyQuests` directory AND your database (if using one).
            - Test beforehand on a separate server than your production one.
            
            ---
            // pretty changelog here
          files: |
            target/*.jar

      - name: Prepare a release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'push' && github.ref_name == github.event.repository.default_branch
        with:
          prerelease: false
          draft: true
          name: "${{ github.ref_name }}"
          tag_name: "${{ github.ref_name }}"
          target_commitish: ${{ github.sha }}
          generate_release_notes: true
          files: |
            target/*.jar
