name: Build

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - .github/**
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDKs
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: |
            21
          # maybe necessary to add more since we want to compile for lower?
          cache: maven
      
      - name: Download private dependencies
        run: |
          mkdir jars
          curl -s https://skytasul.fr/protected/bq-jars.tar.gz --header 'Token: ${{ secrets.PrivateDownloadToken }}' --output - | tar xzfv - --directory ./jars

      - name: Install private dependencies
        run: "./integrations/libs.sh mvn ./jars"

      - name: Install missing dependencies
        run: |
          curl -s https://skytasul.fr/SpigotUpdateChecker-3.0.3-offline.jar -o ./jars/SpigotUpdateChecker-3.0.3-offline.jar
          mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=./jars/SpigotUpdateChecker-3.0.3-offline.jar
          curl -s https://skytasul.fr/ConfigUpdater-2.2-SNAPSHOT-offline.jar -o ./jars/ConfigUpdater-2.2-SNAPSHOT-offline.jar
          mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=./jars/ConfigUpdater-2.2-SNAPSHOT-offline.jar

      - name: Build and package with Maven
        run: |
          profile=$([ "${{ github.ref_name }}" == "${{ github.event.repository.default_branch }}" ] && echo "release" || echo "devbuild")
          echo "Building with profile $profile"
          mvn -B clean package --file pom.xml -Dbuild.number=${{ github.run_number }} -P $profile
    
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: |
            target/*.jar
