name: Dev Build

on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed
    branches:
      - master
      - release/*

jobs:
  prepare:
    name: Prepare GH release
    runs-on: "ubuntu-latest"
    steps:
      - name: Download artifact
        id: artifact
        uses: actions/download-artifact@v8
        with:
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}

      - name: Compute build number
        id: build-number
        run: |
          run_number=${{ github.run_number }}
          starting_number=131
          echo "BUILD_NUMBER=$((run_number + starting_number))" >> "$GITHUB_OUTPUT"

      - name: Prepare a pre-release
        uses: softprops/action-gh-release@v3
        if: github.event.workflow_run.head_branch != github.event.repository.default_branch
        with:
          prerelease: true
          draft: true
          name: "${{ github.event.workflow_run.head_branch }} - build ${{ steps.build-number.outputs.BUILD_NUMBER }}"
          tag_name: "build/${{ steps.build-number.outputs.BUILD_NUMBER }}"
          target_commitish: ${{ github.event.workflow_run.head_sha }}
          generate_release_notes: true
          body: |-
            ### Note
            This is a **dev build** and not a release. Please use with care!
            - Backup your prior data before installing: both the `/plugins/BeautyQuests` directory AND your database (if using one).
            - Test beforehand on a separate server than your production one.
            
            ---
            // pretty changelog here
          files: |
            ${{ steps.artifact.outputs.download-path }}/*.jar

      - name: Prepare a release
        uses: softprops/action-gh-release@v3
        if: github.event.workflow_run.head_branch == github.event.repository.default_branch
        with:
          prerelease: false
          draft: true
          tag_name: "${{ github.event.workflow_run.head_branch }}"
          target_commitish: ${{ github.event.workflow_run.head_sha }}
          generate_release_notes: true
          files: |
            ${{ steps.artifact.outputs.download-path }}/*.jar