name: Dev Build

on:
  push:
    branches:
      - release/*
    paths-ignore:
      - .github/**
      - docs/**

jobs:
  prepare-build:
    runs-on: "ubuntu-slim"
    outputs:
      build-number: ${{ steps.build-number.outputs.BUILD_NUMBER }}
    steps:
      - name: Compute build number
        id: build-number
        run: |
          run_number=${{ github.run_number }}
          number_delta=${{ vars.DEV_BUILD_NUMBER_DELTA || '0' }}
          build_number=$((run_number + number_delta))
          echo "::notice::Build number: $build_number"
          echo "BUILD_NUMBER=$build_number" >> "$GITHUB_OUTPUT"

  build:
    needs:
      - prepare-build
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      build-number: ${{ fromJSON(needs.prepare-build.outputs.build-number) }}

  prepare-release:
    name: Prepare GH release
    needs:
      - prepare-build
      - build
    runs-on: "ubuntu-latest"
    steps:
      - name: Download artifact
        id: artifact
        uses: actions/download-artifact@v8

      - name: Prepare a pre-release
        uses: softprops/action-gh-release@v3
        with:
          prerelease: true
          draft: true
          name: "${{ github.ref_name }} - build ${{ needs.prepare-build.outputs.build-number}}"
          tag_name: "${{ needs.build.outputs.plugin-version }}"
          target_commitish: ${{ github.sha }}
          generate_release_notes: true
          body: |-
            ### Note
            This is a **dev build** and not a release. Please use with care!
            - Backup your prior data before installing: both the `/plugins/BeautyQuests` directory AND your database (if using one).
            - Test beforehand on a separate server than your production one.

            ---
            // pretty changelog here
          files: |
            ${{ steps.artifact.outputs.download-path }}/*.jar
