name: Publish version

on:
  release:
    types: [published]

jobs:
  notify:
    name: Send notifications
    runs-on: ubuntu-latest
    steps:
      - name: Send dev build notification on Discord
        uses: sarisia/actions-status-discord@v1
        if: ${{ github.event.release.prerelease }}
        with:
          webhook: ${{ secrets.WEBHOOK_URL }}
          nodetail: true
          title: "BeautyQuests - ${{ github.event.release.name }}"
          url: ${{ github.event.release.html_url }}
          color: '0x3498db'
          description: |
            New *BeautyQuests* dev build available!

            ## Changelog
            ${{ github.event.release.body }}

            ## Download
            Download the dev build here:
            - [${{ github.event.release.assets[0].name }}](${{ github.event.release.assets[0].browser_download_url }})

      - name: Send release notification on Discord
        uses: sarisia/actions-status-discord@v1
        if: ${{ !github.event.release.prerelease }}
        with:
          webhook: ${{ secrets.WEBHOOK_URL }}
          nodetail: true
          title: "BeautyQuests - ${{ github.event.release.name }}"
          url: ${{ github.event.release.html_url }}
          color: '0x28b463'
          description: |
            New *BeautyQuests* version available!

            Click [here](${{ github.event.release.html_url }}) to see the changelog and download the new version!

  publish:
    name: Publish version on platforms
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        run: |
          curl ${{ github.event.release.assets[0].browser_download_url }} --output ${{ github.event.release.assets[0].name }}

      - parallel:
        - name: Upload to Modrinth
          uses: cloudnode-pro/modrinth-publish@v2
          with:
            token: ${{ secrets.MODRINTH_TOKEN }}
            project: ZbvwkXKZ
            name: "${{ github.event.release.name }}"
            version: "${{ github.event.release.tag_name }}"
            changelog: "${{ github.event.release.body }}"
            game-versions: |-
              1.20.6
              1.21.x
              26.1.x
              26.2.x
            status: "draft"
            channel: ${{ github.event.release.prerelease && 'alpha' || 'release' }}
            loaders: |-
              paper
            files: "${{ github.event.release.assets[0].name }}"

        - name: Upload to Hangar
          uses: milkdrinkers/Hangar-Publish@v2
          continue-on-error: true
          with:
            api_token: ${{ secrets.HANGAR_TOKEN }}
            slug: 'BeautyQuests'
            version: "${{ github.event.release.tag_name }}"
            channel: ${{ github.event.release.prerelease && 'Development' || 'Release' }}
            description: "${{ github.event.release.body }}"
            platform_dependencies: |
              {
                "PAPER": [">=1.20.6"]
              }
            files: |
              [
                {
                  "externalUrl": "${{ github.event.release.assets[0].browser_download_url }}",
                  "url": true,
                  "platforms": ["PAPER"]
                }
              ]
