name: Release update

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Send dev build notification on Discord
        uses: sarisia/actions-status-discord@v1
        if: github.event.release.prerelease
        with:
          webhook: ${{ secrets.WEBHOOK_URL }}
          nodetail: true
          title: "New *BeautyQuests* dev build available!"
          url: ${{ github.event.release.url }}
          color: '0x3498db'
          description: |
            # ${{ github.event.release.name }}

            ## Changelog
            ${{ github.event.release.body }}

            Click [here](${{ github.event.release.url }}) to download the dev build!

      - name: Send release notification on Discord
        uses: sarisia/actions-status-discord@v1
        if: !github.event.release.prerelease
        with:
          webhook: ${{ secrets.WEBHOOK_URL }}
          nodetail: true
          title: "New *BeautyQuests* version available!"
          url: ${{ github.event.release.url }}
          color: '0x28b463'
          description: |
            # ${{ github.event.release.name }}

            Click [here](${{ github.event.release.url }}) to see
            the changelog and download the new version!
